-- Drop the tables in reverse order of creation (to handle foreign key constraints)
DROP TABLE IF EXISTS MARKET_FORECAST_T;
DROP TABLE IF EXISTS REGIONAL_MARKET_STAT_T;
DROP TABLE IF EXISTS MARKET_DEMAND_SUPPLY_T;
DROP TABLE IF EXISTS MARKET_PRICE_TREND_T; 