CREATE TABLE PRODUCTION_HISTORY_T (
  HistoryID INT PRIMARY KEY AUTO_INCREMENT,
  ProductID INT NOT NULL,
  Year YEAR NOT NULL,
  Acreage INT,
  Yield DECIMAL(5,2),
  CostPerAcre DECIMAL(10,2),
  PricePerTon DECIMAL(10,2),
  CONSTRAINT FK_PRODUCTION_HISTORY_PRODUCT_PRODUCTID FOREIGN KEY (ProductID) REFERENCES PRODUCT_T(ProductID)
);
