export const DUMMY_DASHBOARD_DATA = [
  {
    id: '1',
    name: 'Rice',
    category: 'Grains',
    inventory: 1240,
    price: 25.99,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '2',
    name: 'Wheat',
    category: 'Grains',
    inventory: 850,
    price: 18.5,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '3',
    name: 'Corn',
    category: 'Grains',
    inventory: 1120,
    price: 15.75,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '4',
    name: 'Tomatoes',
    category: 'Vegetables',
    inventory: 320,
    price: 32.0,
    method: 'Organic',
    status: 'Low stock',
  },
  {
    id: '5',
    name: 'Potatoes',
    category: 'Vegetables',
    inventory: 750,
    price: 12.25,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '6',
    name: 'Onions',
    category: 'Vegetables',
    inventory: 480,
    price: 8.99,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '7',
    name: 'Apples',
    category: 'Fruits',
    inventory: 280,
    price: 45.75,
    method: 'Organic',
    status: 'Low stock',
  },
  {
    id: '8',
    name: 'Oranges',
    category: 'Fruits',
    inventory: 320,
    price: 38.5,
    method: 'Organic',
    status: 'Low stock',
  },
  {
    id: '9',
    name: 'Bananas',
    category: 'Fruits',
    inventory: 550,
    price: 21.99,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '10',
    name: 'Soybeans',
    category: 'Legumes',
    inventory: 920,
    price: 28.25,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '11',
    name: 'Chickpeas',
    category: 'Legumes',
    inventory: 450,
    price: 32.75,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '12',
    name: 'Lentils',
    category: 'Legumes',
    inventory: 380,
    price: 27.5,
    method: 'Conventional',
    status: 'Low stock',
  },
  {
    id: '13',
    name: 'Carrots',
    category: 'Vegetables',
    inventory: 620,
    price: 10.25,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '14',
    name: 'Spinach',
    category: 'Vegetables',
    inventory: 180,
    price: 22.99,
    method: 'Organic',
    status: 'Low stock',
  },
  {
    id: '15',
    name: 'Barley',
    category: 'Grains',
    inventory: 780,
    price: 16.5,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '16',
    name: 'Bell Peppers',
    category: 'Vegetables',
    inventory: 350,
    price: 24.5,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '17',
    name: 'Cucumbers',
    category: 'Vegetables',
    inventory: 420,
    price: 13.5,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '18',
    name: 'Strawberries',
    category: 'Fruits',
    inventory: 180,
    price: 39.5,
    method: 'Organic',
    status: 'Low stock',
  },
  {
    id: '19',
    name: 'Blueberries',
    category: 'Fruits',
    inventory: 0,
    price: 45.0,
    method: 'Organic',
    status: 'Out of stock',
  },
  {
    id: '20',
    name: 'Watermelon',
    category: 'Fruits',
    inventory: 650,
    price: 7.5,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '21',
    name: 'Pineapple',
    category: 'Fruits',
    inventory: 320,
    price: 29.5,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '22',
    name: 'Broccoli',
    category: 'Vegetables',
    inventory: 410,
    price: 21.5,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '23',
    name: 'Cauliflower',
    category: 'Vegetables',
    inventory: 250,
    price: 22.5,
    method: 'Organic',
    status: 'Low stock',
  },
  {
    id: '24',
    name: 'Sweet Potato',
    category: 'Vegetables',
    inventory: 580,
    price: 14.5,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '25',
    name: 'Garlic',
    category: 'Vegetables',
    inventory: 740,
    price: 32.5,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '26',
    name: 'Kiwi',
    category: 'Fruits',
    inventory: 220,
    price: 31.5,
    method: 'Organic',
    status: 'Low stock',
  },
  {
    id: '27',
    name: 'Mangoes',
    category: 'Fruits',
    inventory: 380,
    price: 28.5,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '28',
    name: 'Avocados',
    category: 'Fruits',
    inventory: 290,
    price: 42.5,
    method: 'Organic',
    status: 'In stock',
  },
  {
    id: '29',
    name: 'Zucchini',
    category: 'Vegetables',
    inventory: 340,
    price: 15.75,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '30',
    name: 'Cabbage',
    category: 'Vegetables',
    inventory: 520,
    price: 11.25,
    method: 'Conventional',
    status: 'In stock',
  },
  {
    id: '31',
    name: 'Pears',
    category: 'Fruits',
    inventory: 410,
    price: 23.5,
    method: 'Organic',
    status: 'In stock',
  },
];
