CREATE TABLE IF NOT EXISTS ZIP_CODE (Zip VARCHAR(10) PRIMARY KEY, City VARCHAR(100));

CREATE TABLE IF NOT EXISTS LAND_USAGE (
	Year INT PRIMARY KEY,
	Type VARCHAR(100),
	Area FLOAT,
	Quantity INT,
	Source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS NUTRITION_DATA (
	Year INT PRIMARY KEY,
	Type VARCHAR(100),
	Quantity INT,
	Price FLOAT
);

CREATE TABLE IF NOT EXISTS GDP (
	Year INT PRIMARY KEY,
	Population BIGINT,
	GDP DECIMAL(15, 2),
	Source VARCHAR(255)
);