CREATE TABLE IF NOT EXISTS WAREHOUSE (
	WarehouseID INT PRIMARY KEY AUTO_INCREMENT,
	WarehouseName VARCHAR(100),
	WarehouseType VARCHAR(100),
	AddressLine1 VARCHAR(200),
	AddressLine2 VARCHAR(200),
	Zip VARCHAR(10),
	Capacity INT,
	TemperatureControlled BOOLEAN,
	FOREIGN KEY (Zip) REFERENCES ZIP_CODE (Zip),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS WAREHOUSE_PRODUCT_TYPE (
	ProductTypeID INT PRIMARY KEY AUTO_INCREMENT,
	ProductType VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS WAREHOUSE_PRODUCT (
	WarehouseID INT,
	ProductTypeID INT,
	FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE (WarehouseID),
	FOREIGN KEY (ProductTypeID) REFERENCES WAREHOUSE_PRODUCT_TYPE (ProductTypeID)
);