CREATE OR REPLACE PROCEDURE create_customer (
    IN p_UserID INT
)
BEGIN
    INSERT INTO CUSTOMER_T (UserID)
    VALUES (p_UserID);
END;
--SQLEND

CREATE OR REPLACE PROCEDURE get_all_customers()
BEGIN
    SELECT u.*
    FROM USER_T u
    JOIN CUSTOMER_T c ON u.UserID = c.UserID;
END;
--SQLEND

CREATE OR REPLACE PROCEDURE get_customer_by_id (
    IN p_UserID INT
)
BEGIN
    SELECT u.*
    FROM USER_T u
    JOIN CUSTOMER_T c ON u.UserID = c.UserID
    WHERE u.UserID = p_UserID;
END;
--SQLEND

CREATE OR REPLACE PROCEDURE delete_customer (
    IN p_UserID INT
)
BEGIN
    DELETE FROM CUSTOMER_T WHERE UserID = p_UserID;
END;
--SQLEND