CREATE OR REPLACE PROCEDURE create_customer (
    IN p_UserID INT
)
BEGIN
    INSERT INTO CUSTOMER (UserID)
    VALUES (p_UserID);
END;
--SQLEND

CREATE OR REPLACE PROCEDURE get_all_customers()
BEGIN
    SELECT u.*
    FROM USERS u
    JOIN CUSTOMER c ON u.UserID = c.UserID;
END;
--SQLEND

CREATE OR REPLACE PROCEDURE get_customer_by_id (
    IN p_UserID INT
)
BEGIN
    SELECT u.*
    FROM USERS u
    JOIN CUSTOMER c ON u.UserID = c.UserID
    WHERE u.UserID = p_UserID;
END;
--SQLEND

CREATE OR REPLACE PROCEDURE delete_customer (
    IN p_UserID INT
)
BEGIN
    DELETE FROM CUSTOMER WHERE UserID = p_UserID;
END;
--SQLEND