CREATE TABLE IF NOT EXISTS ZIP_CODE_T (Zip VARCHAR(10) PRIMARY KEY, City VARCHAR(100));
--SQLEND
CREATE TABLE IF NOT EXISTS LAND_USAGE_T (
  Year INT PRIMARY KEY,
  Type VARCHAR(100),
  Area FLOAT,
  Quantity INT,
  Source VARCHAR(255)
);
--SQLEND
CREATE TABLE IF NOT EXISTS NUTRITION_DATA_T (
  Year INT PRIMARY KEY,
  Type VARCHAR(100),
  Quantity INT,
  Price FLOAT
);
--SQLEND
CREATE TABLE IF NOT EXISTS GDP_T (
  Year INT PRIMARY KEY,
  Population BIGINT,
  GDP DECIMAL(15, 2),
  Source VARCHAR(255)
);
--SQLEND
