CREATE TABLE IF NOT EXISTS USER_T (
	UserID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL,
	Phone VARCHAR(20),
	AddressLine1 VARCHAR(255),
	AddressLine2 VARCHAR(255),
	Zip VARCHAR(10),
	UserType ENUM (
		'farmer',
		'retailer',
		'wholesaler',
		'customer',
		'admin'
	) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_USER_ZIP_COUNTRY FOREIGN KEY (Zip) REFERENCES ZIP_CODE_T (Zip) ON DELETE SET NULL
);
--SQLEND
CREATE TABLE IF NOT EXISTS FARMER_T (
	UserID INT NOT NULL PRIMARY KEY,
	Gender ENUM ('male', 'female', 'other'),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_FARMER_USER_USERID FOREIGN KEY (UserID) REFERENCES USER_T (UserID) ON DELETE CASCADE
);
--SQLEND
CREATE TABLE IF NOT EXISTS CUSTOMER_T (
	UserID INT NOT NULL PRIMARY KEY,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_CUSTOMER_USER_USERID FOREIGN KEY (UserID) REFERENCES USER_T (UserID) ON DELETE CASCADE
);
--SQLEND
CREATE TABLE IF NOT EXISTS VENDOR_T (
	LicenseID INT PRIMARY KEY AUTO_INCREMENT,
	UserID INT,
	RegistrationDate DATETIME,
	VendorType ENUM ('wholesaler', 'retailer'),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_VENDOR_USER_USERID FOREIGN KEY (UserID) REFERENCES USER_T (UserID) ON DELETE CASCADE
);
--SQLEND
CREATE TABLE IF NOT EXISTS WHOLESALER_T (
	WLicenseID INT NOT NULL PRIMARY KEY,
	MinOrderQuantity INT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_WHOLESALER_USER_USERID FOREIGN KEY (WLicenseID) REFERENCES VENDOR_T (LicenseID) ON DELETE CASCADE
);
--SQLEND
CREATE TABLE IF NOT EXISTS RETAILER_T (
	RLicenseID INT NOT NULL PRIMARY KEY,
	StoreType VARCHAR(100),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_RETAILER_USER_USERID FOREIGN KEY (RLicenseID) REFERENCES VENDOR_T (LicenseID) ON DELETE CASCADE
);
--SQLEND