CREATE TABLE IF NOT EXISTS PRODUCT_T (
	ProductID INT PRIMARY KEY AUTO_INCREMENT,
	ProductName VARCHAR(100),
	Quantity INT,
	ShelfLifeDays INT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_VARIETY_T (
	ProductID INT,
	Variety VARCHAR(100),
	CONSTRAINT PK_PRODUCT_VARIETY_ID PRIMARY KEY (ProductID, Variety),
	CONSTRAINT FK_PRODUCT_VARIETY_PRODUCT_PRODUCTID FOREIGN KEY (ProductID) REFERENCES PRODUCT_T (ProductID) ON DELETE CASCADE
);

--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY_T (
	ProductID INT,
	Category VARCHAR(100),
	CONSTRAINT PK_PRODUCT_CATEGORY_ID PRIMARY KEY (ProductID, Category),
	CONSTRAINT FK_PRODUCT_CATEGORY_PRODUCT_PRODUCTID FOREIGN KEY (ProductID) REFERENCES PRODUCT_T (ProductID) ON DELETE CASCADE
);
--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_SEASONALITY_T (
	ProductID INT,
	Seasonality VARCHAR(100),
	CONSTRAINT PK_PRODUCT_SEASONALITY_ID PRIMARY KEY (ProductID, Seasonality),
	CONSTRAINT FK_PRODUCT_SEASONALITY_PRODUCT_PRODUCTID FOREIGN KEY (ProductID) REFERENCES PRODUCT_T (ProductID) ON DELETE CASCADE
);
--SQLEND
CREATE TABLE IF NOT EXISTS FARM_PRODUCT_T (
	FarmerID INT,
	ProductID INT,
	Quantity INT,
	ProductionDate DATETIME,
	CONSTRAINT PK_FARM_PRODUCT_ID PRIMARY KEY (FarmerID, ProductID, ProductionDate),
	CONSTRAINT FK_FARM_PRODUCT_FARMER_USERID FOREIGN KEY (FarmerID) REFERENCES FARMER_T (UserID) ON DELETE CASCADE,
	CONSTRAINT FK_FARM_PRODUCT_PRODUCT_PRODUCTID FOREIGN KEY (ProductID) REFERENCES PRODUCT_T (ProductID) ON DELETE CASCADE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND
CREATE TABLE IF NOT EXISTS FARM_PRODUCT_BATCH_T (
	BatchID INT PRIMARY KEY AUTO_INCREMENT,
	Quantity INT,
	BatchDate DATETIME,
	FarmerID INT,
	ProductID INT,
	CONSTRAINT FK_FARM_PRODUCT_BATCH_FARMER_USERID FOREIGN KEY (FarmerID) REFERENCES FARMER_T (UserID) ON DELETE CASCADE,
	CONSTRAINT FK_FARM_PRODUCT_BATCH_PRODUCT_PRODUCTID FOREIGN KEY (ProductID) REFERENCES PRODUCT_T (ProductID) ON DELETE CASCADE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND