CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY_T (
  CategoryID INT PRIMARY KEY AUTO_INCREMENT,
  CategoryName VARCHAR(100) UNIQUE NOT NULL
);
--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_VARIETY_T (
  VarietyID INT PRIMARY KEY AUTO_INCREMENT,
  VarietyName VARCHAR(100) UNIQUE NOT NULL,
  CategoryID INT,
  CONSTRAINT FK_PRODUCT_VARIETY_CATEGORY_CATEGORYID FOREIGN KEY (CategoryID) REFERENCES PRODUCT_CATEGORY_T(CategoryID) ON DELETE SET NULL
);
--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_SEASONALITY_T (
  SeasonalityID INT PRIMARY KEY AUTO_INCREMENT,
  SeasonalityName VARCHAR(100) UNIQUE NOT NULL
);
--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_T (
  ProductID INT PRIMARY KEY AUTO_INCREMENT,
  ProductName VARCHAR(100) NOT NULL,
  Quantity INT,
  ShelfLifeDays INT,
  VarietyID INT,
  SeasonalityID INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_PRODUCT_PRODUCT_VARIETY_VARIETYID FOREIGN KEY (VarietyID) REFERENCES PRODUCT_VARIETY_T(VarietyID) ON DELETE SET NULL,
  CONSTRAINT FK_PRODUCT_PRODUCT_SEASONALITY_SEASONALITYID FOREIGN KEY (SeasonalityID) REFERENCES PRODUCT_SEASONALITY_T(SeasonalityID) ON DELETE SET NULL
);
--SQLEND
CREATE TABLE IF NOT EXISTS FARM_PRODUCT_T (
	FarmerID INT,
	ProductID INT,
	Quantity INT,
	ProductionDate DATETIME,
	CONSTRAINT PK_FARM_PRODUCT_ID PRIMARY KEY (FarmerID, ProductID, ProductionDate),
	CONSTRAINT FK_FARM_PRODUCT_FARMER_USERID FOREIGN KEY (FarmerID) REFERENCES FARMER_T (UserID) ON DELETE CASCADE,
	CONSTRAINT FK_FARM_PRODUCT_PRODUCT_PRODUCTID FOREIGN KEY (ProductID) REFERENCES PRODUCT_T (ProductID) ON DELETE CASCADE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND
CREATE TABLE IF NOT EXISTS FARM_PRODUCT_BATCH_T (
	BatchID INT PRIMARY KEY AUTO_INCREMENT,
	Quantity INT,
	BatchDate DATETIME,
	FarmerID INT,
	ProductID INT,
	CONSTRAINT FK_FARM_PRODUCT_BATCH_FARMER_USERID FOREIGN KEY (FarmerID) REFERENCES FARMER_T (UserID) ON DELETE CASCADE,
	CONSTRAINT FK_FARM_PRODUCT_BATCH_PRODUCT_PRODUCTID FOREIGN KEY (ProductID) REFERENCES PRODUCT_T (ProductID) ON DELETE CASCADE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND