CREATE TABLE IF NOT EXISTS PRODUCT (
	ProductID INT PRIMARY KEY AUTO_INCREMENT,
	ProductName VARCHAR(100),
	Quantity INT,
	ShelfLifeDays INT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_VARIETY (
	ProductID INT,
	Variety VARCHAR(100),
	FOREIGN KEY (ProductID) REFERENCES PRODUCT (ProductID)
);
--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY (
	ProductID INT,
	Category VARCHAR(100),
	FOREIGN KEY (ProductID) REFERENCES PRODUCT (ProductID)
);
--SQLEND
CREATE TABLE IF NOT EXISTS PRODUCT_SEASONALITY (
	ProductID INT,
	Seasonality VARCHAR(100),
	FOREIGN KEY (ProductID) REFERENCES PRODUCT (ProductID)
);
--SQLEND
CREATE TABLE IF NOT EXISTS FARM_PRODUCT (
	FarmerID INT,
	ProductID INT,
	Quantity INT,
	ProductionDate DATETIME,
	FOREIGN KEY (FarmerID) REFERENCES FARMER (UserID),
	FOREIGN KEY (ProductID) REFERENCES PRODUCT (ProductID),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND
CREATE TABLE IF NOT EXISTS FARM_PRODUCT_BATCH (
	BatchID INT PRIMARY KEY AUTO_INCREMENT,
	Quantity INT,
	BatchDate DATETIME,
	FarmerID INT,
	ProductID INT,
	FOREIGN KEY (FarmerID) REFERENCES FARMER (UserID),
	FOREIGN KEY (ProductID) REFERENCES PRODUCT (ProductID),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND