CREATE TABLE IF NOT EXISTS WAREHOUSE_T (
	WarehouseID INT PRIMARY KEY AUTO_INCREMENT,
	WarehouseName VARCHAR(100),
	WarehouseType VARCHAR(100),
	AddressLine1 VARCHAR(200),
	AddressLine2 VARCHAR(200),
	Zip VARCHAR(10),
	Capacity INT,
	TemperatureControlled BOOLEAN,
	CONSTRAINT FK_WAREHOUSE_ZIP_COUNTRY FOREIGN KEY (Zip) REFERENCES ZIP_CODE_T (Zip) ON DELETE SET NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--SQLEND
CREATE TABLE IF NOT EXISTS WAREHOUSE_PRODUCT_T (
	WarehouseID INT,
	ProductID INT,
	StockQuantity INT DEFAULT 0,
	ProductCapacity INT NOT NULL, -- Maximum capacity for this product in this warehouse
	LastStockedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_WAREHOUSE_PRODUCT_ID PRIMARY KEY (WarehouseID, ProductID),
	CONSTRAINT FK_WAREHOUSE_PRODUCT_WAREHOUSE FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE_T (WarehouseID) ON DELETE CASCADE,
	CONSTRAINT FK_WAREHOUSE_PRODUCT_PRODUCT FOREIGN KEY (ProductID) REFERENCES PRODUCT_T (ProductID) ON DELETE CASCADE
);
--SQLEND