CREATE TABLE IF NOT EXISTS DELIVERY_T (
	DeliveryID INT PRIMARY KEY AUTO_INCREMENT,
	DeliveryDate DATETIME,
	TransportMode VARCHAR(100),
	Status VARCHAR(100),
	Type VARCHAR(100),
	BatchID INT,
	WarehouseID INT,
	LicenseID INT,
	CustomerID INT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_DELVERY_FARM_PRODUCT_BATCH_BATCHID FOREIGN KEY (BatchID) REFERENCES FARM_PRODUCT_BATCH_T (BatchID),
	CONSTRAINT FK_DELVERY_WAREHOUSE_WAREHOUSEID FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE_T (WarehouseID),
	CONSTRAINT FK_DELVERY_VENDOR_LICENSEID FOREIGN KEY (LicenseID) REFERENCES VENDOR_T (LicenseID),
	CONSTRAINT FK_DELVERY_USER_USERID FOREIGN KEY (CustomerID) REFERENCES USER_T (UserID)
);
--SQLEND